## Staging grain transporation costs from USDA data for trucks

In [7]:
import requests
import pandas as pd
from pprint import pprint
#from config import api_key

In [39]:
#Create the URL and params
url="https://agtransport.usda.gov/resource/8uye-ieij.json?"
sample_years=["2018", "2019","2020","2021","2022"]
param1="$query=select%20year,month,sum(truck)%20where%20year="
param2="%20group%20by%20year,month%20order%20by%20year,month"

In [46]:
#Get the payload
years=[]
months=[]
ttons=[]

for year in sample_years:
        params=param1+year+param2
        response = requests.get(url,params=params).json()
        for trucking_year in response:
                years.append(trucking_year['year'])
                months.append(trucking_year['month'])
                ttons.append(trucking_year['sum_truck'])
grain_trucking_volume_df=pd.DataFrame(zip(years,months,ttons))
grain_trucking_volume_df.columns=["Year","Month","Grain Moved (000) tons"]
grain_trucking_volume_df

    Year Month Grain Moved (000) tons
0   2018     1                    808
1   2018     2                    818
2   2018     3                    802
3   2018     4                   1038
4   2018     5                    871
5   2018     6                    873
6   2018     7                   1085
7   2018     8                    864
8   2018     9                   1098
9   2018    10                    907
10  2018    11                    886
11  2018    12                   1048
12  2019     1                    800
13  2019     2                    805
14  2019     3                   1033
15  2019     4                    841
16  2019     5                    848
17  2019     6                   1032
18  2019     7                    818
19  2019     8                    806
20  2019     9                   1012
21  2019    10                    820
22  2019    11                    824
23  2019    12                   1025
24  2020     1                    819
25  2020     2                    780
26  2020     3                    915
27  2020     4                    669
28  2020     5                    802
29  2020     6                    648
30  2020     7                    654
31  2020     8                    816
32  2020     9                    648
33  2020    10                    641
34  2020    11                    816
35  2020    12                    695
36  2021     1                    903
37  2021     2                    787
38  2021     3                    851
39  2021     4                    841
40  2021     5                   1079
41  2021     6                    883
42  2021     7                    896
43  2021     8                   1124
44  2021     9                    908
45  2021    10                   1219
46  2021    11                   1001
47  2021    12                    978
48  2022     1                   1249
49  2022     2                   1082
50  2022     3                   1370
51  2022     4                   1373
52  2022     5                   1870
53  2022     6                   1545
54  2022     7                   1819
55  2022     8                   1337
56  2022     9                   1340
57  2022    10                   1749
58  2022    11                   1411
59  2022    12                   1264

In [47]:
#Save the dataframe to a csv in the staging folder
grain_trucking_volume_df.to_csv("staging/grain_trucking_volume.csv")

In [49]:
grain_tucking_volume_df = pd.read_csv("staging/grain_trucking_volume.csv")
grain_trucking_volume_df

    Year Month Grain Moved (000) tons
0   2018     1                    808
1   2018     2                    818
2   2018     3                    802
3   2018     4                   1038
4   2018     5                    871
5   2018     6                    873
6   2018     7                   1085
7   2018     8                    864
8   2018     9                   1098
9   2018    10                    907
10  2018    11                    886
11  2018    12                   1048
12  2019     1                    800
13  2019     2                    805
14  2019     3                   1033
15  2019     4                    841
16  2019     5                    848
17  2019     6                   1032
18  2019     7                    818
19  2019     8                    806
20  2019     9                   1012
21  2019    10                    820
22  2019    11                    824
23  2019    12                   1025
24  2020     1                    819
25  2020     2                    780
26  2020     3                    915
27  2020     4                    669
28  2020     5                    802
29  2020     6                    648
30  2020     7                    654
31  2020     8                    816
32  2020     9                    648
33  2020    10                    641
34  2020    11                    816
35  2020    12                    695
36  2021     1                    903
37  2021     2                    787
38  2021     3                    851
39  2021     4                    841
40  2021     5                   1079
41  2021     6                    883
42  2021     7                    896
43  2021     8                   1124
44  2021     9                    908
45  2021    10                   1219
46  2021    11                   1001
47  2021    12                    978
48  2022     1                   1249
49  2022     2                   1082
50  2022     3                   1370
51  2022     4                   1373
52  2022     5                   1870
53  2022     6                   1545
54  2022     7                   1819
55  2022     8                   1337
56  2022     9                   1340
57  2022    10                   1749
58  2022    11                   1411
59  2022    12                   1264