## Staging grain transporation costs from USDA data for trucks

In [15]:
import requests
import pandas as pd
from pprint import pprint
#from config import api_key

In [16]:
#Create the URL and params
url="https://agtransport.usda.gov/resource/8uye-ieij.json?"
sample_years=["2018", "2019","2020","2021","2022"]
param1="$query=select%20year,month,sum(truck)%20where%20year="
param2="%20group%20by%20year,month%20order%20by%20year,month"

In [17]:
#Get the payload

for year in sample_years:
        years=[]
        months=[]
        ttons=[]
        params=param1+year+param2
        response = requests.get(url,params=params).json()
        for trucking_year in response:
                years.append(trucking_year['year'])
                months.append(trucking_year['month'])
                ttons.append(trucking_year['sum_truck'])
grain_trucking_volume_df=pd.DataFrame(zip(years,months,ttons))
grain_trucking_volume_df.columns=["Year","Month","Grain Moved (000) tons"]
#grain_trucking_volume_df.set_index('Year')
grain_trucking_volume_df

    Year Month Grain Moved (000) tons
0   2022     1                   1249
1   2022     2                   1082
2   2022     3                   1370
3   2022     4                   1373
4   2022     5                   1870
5   2022     6                   1545
6   2022     7                   1819
7   2022     8                   1337
8   2022     9                   1340
9   2022    10                   1749
10  2022    11                   1411
11  2022    12                   1264

In [5]:
#Save the dataframe to a csv in the staging folder
grain_trucking_volume_df.to_csv("staging/grain_trucking_volume.csv",index=False)

In [6]:
grain_trucking_volume_df = pd.read_csv("staging/grain_trucking_volume.csv")
grain_trucking_volume_df

    Year  Month  Grain Moved (000) tons
0   2018      1                     808
1   2018      2                     818
2   2018      3                     802
3   2018      4                    1038
4   2018      5                     871
5   2018      6                     873
6   2018      7                    1085
7   2018      8                     864
8   2018      9                    1098
9   2018     10                     907
10  2018     11                     886
11  2018     12                    1048
12  2019      1                     800
13  2019      2                     805
14  2019      3                    1033
15  2019      4                     841
16  2019      5                     848
17  2019      6                    1032
18  2019      7                     818
19  2019      8                     806
20  2019      9                    1012
21  2019     10                     820
22  2019     11                     824
23  2019     12                    1025
24  2020      1                     819
25  2020      2                     780
26  2020      3                     915
27  2020      4                     669
28  2020      5                     802
29  2020      6                     648
30  2020      7                     654
31  2020      8                     816
32  2020      9                     648
33  2020     10                     641
34  2020     11                     816
35  2020     12                     695
36  2021      1                     903
37  2021      2                     787
38  2021      3                     851
39  2021      4                     841
40  2021      5                    1079
41  2021      6                     883
42  2021      7                     896
43  2021      8                    1124
44  2021      9                     908
45  2021     10                    1219
46  2021     11                    1001
47  2021     12                     978
48  2022      1                    1249
49  2022      2                    1082
50  2022      3                    1370
51  2022      4                    1373
52  2022      5                    1870
53  2022      6                    1545
54  2022      7                    1819
55  2022      8                    1337
56  2022      9                    1340
57  2022     10                    1749
58  2022     11                    1411
59  2022     12                    1264

In [2]:
filepath="Resources/Refrigerated_Truck_Volumes.csv"
refrigerated_truck_volume = pd.read_csv("Resources/Refrigerated_Truck_Volumes.csv")
refrigerated_truck_volume.tail(20)

,date,Weekday,Month,Year,Quarter,Tuesday Week Ending,Tuesday Week Ending Number,Season,Mode,Region,Origin,District,Commodity,"10,000 LBS"
1764811,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,California,California-south,Oxnard District,Misc Herbs,6
1764812,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,California,California-south,Oxnard District,Onions Green,1
1764813,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,California,California-south,Oxnard District,Raspberries,9
1764814,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Canada,Canada,Imports Through Blaine (washington),Cucumbers,1
1764815,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Canada,Canada,Imports Through Buffalo,Cucumbers,0
1764816,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Canada,Canada,Imports Through Buffalo,"Peppers, Bell Type",0
1764817,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Canada,Canada,Imports Through Buffalo,Tomatoes,0
1764818,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Canada,Canada,Imports Through Champlain (new York),Cucumbers,4
1764819,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Canada,Canada,Imports Through Champlain (new York),Tomatoes,5
1764820,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Canada,Canada,Imports Through Detroit,Cucumbers,26
1764821,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Canada,Canada,Imports Through Detroit,"Peppers, Bell Type",0
1764822,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Canada,Canada,Imports Through Detroit,Tomatoes,9
1764823,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Florida,Florida,Florida Districts,Blueberries,42
1764824,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Florida,Florida,Florida Districts,Okra,2
1764825,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Florida,Florida,Florida Districts,Potatoes,262
1764826,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Florida,Florida,Florida Districts,"Watermelons, Seeded",160
1764827,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Florida,Florida,Florida Districts,"Watermelons, Seedless",662
1764828,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Mexico-Texas,Mexico,"Mexico Crossings Through Pharr, Tx",Mangoes,9
1764829,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Mexico-Arizona,Mexico,Mexico Crossings Thru Nogales,Mangoes,29
1764830,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Texas,Texas,Lower Rio Grande Valley,Onions Dry,210

In [8]:
refrig_truck_vol_5_years = refrigerated_truck_volume.loc[(refrigerated_truck_volume['Year']>2017) & (refrigerated_truck_volume['Year'] <2023),:]
refrig_truck_vol_5_years

,date,Weekday,Month,Year,Quarter,Tuesday Week Ending,Tuesday Week Ending Number,Season,Mode,Region,Origin,District,Commodity,"10,000 LBS"
1083781,01/01/2018,1,1,2018,1,01/02/2018,52,2017,Truck,California,California-south,Oxnard District,Strawberries,18
1083782,01/01/2018,1,1,2018,1,01/02/2018,52,2017,Truck,Florida,Florida,Florida Districts,Beans,8
1083783,01/01/2018,1,1,2018,1,01/02/2018,52,2017,Truck,Florida,Florida,Florida Districts,Broccoli,42
1083784,01/01/2018,1,1,2018,1,01/02/2018,52,2017,Truck,Florida,Florida,Florida Districts,Cabbage,104
1083785,01/01/2018,1,1,2018,1,01/02/2018,52,2017,Truck,Florida,Florida,Florida Districts,Celery,82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1728540,12/31/2022,6,12,2022,4,01/03/2023,53,2022,Truck,PNW,Washington,Washington District,Apples,7383
1728541,12/31/2022,6,12,2022,4,01/03/2023,53,2022,Truck,PNW,Washington,Washington District,Pears,1211
1728542,12/31/2022,6,12,2022,4,01/03/2023,53,2022,Truck,Other,Western U.s.,Western U.s. District,"Onions, Processed",519
1728543,12/31/2022,6,12,2022,4,01/03/2023,53,2022,Truck,Great Lakes,Wisconsin,Wisconsin District,Onions Dry,111
1728544,12/31/2022,6,12,2022,4,01/03/2023,53,2022,Truck,Great Lakes,Wisconsin,Wisconsin District,Potatoes,2

In [12]:
print(f"Number of commodities trucked: {refrig_truck_vol_5_years['Commodity'].nunique()}")

Number of commodities trucked: 137

In [13]:
refrig_truck_vol_5_years.to_csv("staging/refrigerated_truck_volume.csv", index=False)