## Staging grain transporation costs from USDA data for trucks

In [1]:
import requests
import pandas as pd
from pprint import pprint

In [2]:
#Create the URL and params
url="https://agtransport.usda.gov/resource/8uye-ieij.json?"
sample_years=["2018", "2019","2020","2021","2022"]
param1="$query=select%20year,month,avg(truck)%20where%20year="
param2="%20group%20by%20year,month%20order%20by%20year,month"

In [3]:
#Loop through each year and get the api response
years=[]
months=[]
priceidx=[]
for year in sample_years:
        params=param1+year+param2
        response = requests.get(url,params=params).json()
        for trucking_year in response:
                
                years.append(trucking_year['year'])
                months.append(trucking_year['month'])
                priceidx.append(float(trucking_year['avg_truck']))

grain_trucking_cost_df=pd.DataFrame(zip(years,months,priceidx))
grain_trucking_cost_df.columns=["Year","Month","Trucking Cost Index"]
grain_trucking_cost_df

    Year Month  Trucking Cost Index
0   2018     1               202.00
1   2018     2               204.50
2   2018     3               200.50
3   2018     4               207.60
4   2018     5               217.75
5   2018     6               218.25
6   2018     7               217.00
7   2018     8               216.00
8   2018     9               219.60
9   2018    10               226.75
10  2018    11               221.50
11  2018    12               209.60
12  2019     1               200.00
13  2019     2               201.25
14  2019     3               206.60
15  2019     4               210.25
16  2019     5               212.00
17  2019     6               206.40
18  2019     7               204.50
19  2019     8               201.50
20  2019     9               202.40
21  2019    10               205.00
22  2019    11               206.00
23  2019    12               205.00
24  2020     1               204.75
25  2020     2               195.00
26  2020     3               183.00
27  2020     4               167.25
28  2020     5               160.40
29  2020     6               162.00
30  2020     7               163.50
31  2020     8               163.20
32  2020     9               162.00
33  2020    10               160.25
34  2020    11               163.20
35  2020    12               173.75
36  2021     1               180.60
37  2021     2               196.75
38  2021     3               212.75
39  2021     4               210.25
40  2021     5               215.80
41  2021     6               220.75
42  2021     7               224.00
43  2021     8               224.80
44  2021     9               227.00
45  2021    10               243.80
46  2021    11               250.25
47  2021    12               244.50
48  2022     1               249.80
49  2022     2               270.50
50  2022     3               342.50
51  2022     4               343.25
52  2022     5               374.00
53  2022     6               386.25
54  2022     7               363.80
55  2022     8               334.25
56  2022     9               335.00
57  2022    10               349.80
58  2022    11               352.75
59  2022    12               316.00

In [4]:
#Save the dataframe to a csv in the staging folder
grain_trucking_cost_df.to_csv("staging/grain_trucking_cost.csv",index=False)

In [5]:
#Read the csv back into a dataframe
grain_trucking_volume_df = pd.read_csv("staging/grain_trucking_cost.csv")
grain_trucking_volume_df

    Year  Month  Trucking Cost Index
0   2018      1               202.00
1   2018      2               204.50
2   2018      3               200.50
3   2018      4               207.60
4   2018      5               217.75
5   2018      6               218.25
6   2018      7               217.00
7   2018      8               216.00
8   2018      9               219.60
9   2018     10               226.75
10  2018     11               221.50
11  2018     12               209.60
12  2019      1               200.00
13  2019      2               201.25
14  2019      3               206.60
15  2019      4               210.25
16  2019      5               212.00
17  2019      6               206.40
18  2019      7               204.50
19  2019      8               201.50
20  2019      9               202.40
21  2019     10               205.00
22  2019     11               206.00
23  2019     12               205.00
24  2020      1               204.75
25  2020      2               195.00
26  2020      3               183.00
27  2020      4               167.25
28  2020      5               160.40
29  2020      6               162.00
30  2020      7               163.50
31  2020      8               163.20
32  2020      9               162.00
33  2020     10               160.25
34  2020     11               163.20
35  2020     12               173.75
36  2021      1               180.60
37  2021      2               196.75
38  2021      3               212.75
39  2021      4               210.25
40  2021      5               215.80
41  2021      6               220.75
42  2021      7               224.00
43  2021      8               224.80
44  2021      9               227.00
45  2021     10               243.80
46  2021     11               250.25
47  2021     12               244.50
48  2022      1               249.80
49  2022      2               270.50
50  2022      3               342.50
51  2022      4               343.25
52  2022      5               374.00
53  2022      6               386.25
54  2022      7               363.80
55  2022      8               334.25
56  2022      9               335.00
57  2022     10               349.80
58  2022     11               352.75
59  2022     12               316.00

In [6]:
# Read the raw csv file for refrigerated truck volume
filepath="Resources/Refrigerated_Truck_Volumes.csv"
refrigerated_truck_volume = pd.read_csv("Resources/Refrigerated_Truck_Volumes.csv")
refrigerated_truck_volume.tail(20)

,date,Weekday,Month,Year,Quarter,Tuesday Week Ending,Tuesday Week Ending Number,Season,Mode,Region,Origin,District,Commodity,"10,000 LBS"
1764811,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,California,California-south,Oxnard District,Misc Herbs,6
1764812,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,California,California-south,Oxnard District,Onions Green,1
1764813,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,California,California-south,Oxnard District,Raspberries,9
1764814,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Canada,Canada,Imports Through Blaine (washington),Cucumbers,1
1764815,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Canada,Canada,Imports Through Buffalo,Cucumbers,0
1764816,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Canada,Canada,Imports Through Buffalo,"Peppers, Bell Type",0
1764817,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Canada,Canada,Imports Through Buffalo,Tomatoes,0
1764818,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Canada,Canada,Imports Through Champlain (new York),Cucumbers,4
1764819,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Canada,Canada,Imports Through Champlain (new York),Tomatoes,5
1764820,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Canada,Canada,Imports Through Detroit,Cucumbers,26
1764821,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Canada,Canada,Imports Through Detroit,"Peppers, Bell Type",0
1764822,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Canada,Canada,Imports Through Detroit,Tomatoes,9
1764823,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Florida,Florida,Florida Districts,Blueberries,42
1764824,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Florida,Florida,Florida Districts,Okra,2
1764825,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Florida,Florida,Florida Districts,Potatoes,262
1764826,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Florida,Florida,Florida Districts,"Watermelons, Seeded",160
1764827,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Florida,Florida,Florida Districts,"Watermelons, Seedless",662
1764828,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Mexico-Texas,Mexico,"Mexico Crossings Through Pharr, Tx",Mangoes,9
1764829,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Mexico-Arizona,Mexico,Mexico Crossings Thru Nogales,Mangoes,29
1764830,04/12/2023,3,4,2023,2,04/18/2023,15,2023,Truck,Texas,Texas,Lower Rio Grande Valley,Onions Dry,210

In [7]:
# Select the data for 5 years from 2018 to 2022
refrig_truck_vol_5_years = refrigerated_truck_volume.loc[(refrigerated_truck_volume['Year']>2017) & (refrigerated_truck_volume['Year'] <2023),:]
refrig_truck_vol_5_years

,date,Weekday,Month,Year,Quarter,Tuesday Week Ending,Tuesday Week Ending Number,Season,Mode,Region,Origin,District,Commodity,"10,000 LBS"
1083781,01/01/2018,1,1,2018,1,01/02/2018,52,2017,Truck,California,California-south,Oxnard District,Strawberries,18
1083782,01/01/2018,1,1,2018,1,01/02/2018,52,2017,Truck,Florida,Florida,Florida Districts,Beans,8
1083783,01/01/2018,1,1,2018,1,01/02/2018,52,2017,Truck,Florida,Florida,Florida Districts,Broccoli,42
1083784,01/01/2018,1,1,2018,1,01/02/2018,52,2017,Truck,Florida,Florida,Florida Districts,Cabbage,104
1083785,01/01/2018,1,1,2018,1,01/02/2018,52,2017,Truck,Florida,Florida,Florida Districts,Celery,82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1728540,12/31/2022,6,12,2022,4,01/03/2023,53,2022,Truck,PNW,Washington,Washington District,Apples,7383
1728541,12/31/2022,6,12,2022,4,01/03/2023,53,2022,Truck,PNW,Washington,Washington District,Pears,1211
1728542,12/31/2022,6,12,2022,4,01/03/2023,53,2022,Truck,Other,Western U.s.,Western U.s. District,"Onions, Processed",519
1728543,12/31/2022,6,12,2022,4,01/03/2023,53,2022,Truck,Great Lakes,Wisconsin,Wisconsin District,Onions Dry,111
1728544,12/31/2022,6,12,2022,4,01/03/2023,53,2022,Truck,Great Lakes,Wisconsin,Wisconsin District,Potatoes,2

In [8]:
# List the commodities that are transported via refrigerated trucks
print(f"Number of commodities trucked: {refrig_truck_vol_5_years['Commodity'].nunique()}")
print(f"Commodities trucked: {refrig_truck_vol_5_years['Commodity'].unique()}")

Number of commodities trucked: 137
Commodities trucked: ['Strawberries' 'Beans' 'Broccoli' 'Cabbage' 'Celery' 'Corn, Sweet'
 'Eggplant' 'Endive' 'Escarole' 'Grapefruit' 'Lettuce, Iceberg'
 'Lettuce, Romaine' 'Oranges' 'Peppers, Bell Type' 'Radishes' 'Squash'
 'Tangelos' 'Tangerines' 'Tomatoes' 'Tomatoes, Cherry'
 'Tomatoes, Grape Type' 'Tomatoes, Plum Type' 'Potatoes' 'Raspberries'
 'Apples' 'Cauliflower' 'Chinese Cabbage' 'Kale Greens' 'Misc Asian'
 'Parsley' 'Lettuce, Boston' 'Lettuce, Green Leaf' 'Lettuce, Processed'
 'Lettuce, Red Leaf' 'Radicchio' 'Spinach' 'Carrots' 'Grapes'
 'Blackberries' 'Brussels Sprouts' 'Onions Green' 'Artichokes' 'Cucumbers'
 'Peppers, Other' 'Onions Dry' 'Asparagus' 'Beets' 'Collard Greens'
 'Misc Herbs' 'Swiss Chard' 'Avocados' 'Bananas' 'Blueberries'
 'Lettuce, Other' 'Misc Tropical' 'Mushrooms' 'Cactus Leaf (nopales)'
 'Cactus Pears' 'Edible Flowers' 'Limes' 'Mixed and Misc Melons' 'Mustard'
 'Papaya' 'Peas Green' 'Peas Other' 'Pineapples' 'Plantains'
 'Salicornia (sea Bean)' 'Vegetables Other' 'Watermelons' 'Honeydews'
 'Huauzontle' 'Kohlrabi' 'Okra' 'Rape Greens' 'Pumpkins'
 'Watermelons, Seedless' 'Turnip Tops Greens' 'Misc Berries' 'Mizuna'
 'Lemons' 'Turnips' 'Guava' "Lamb's Quarters (quilete)" 'Sweet Potatoes'
 'Frisee' 'Dates' 'Carambola, Star Fruit' 'Figs' 'Garlic' 'Clementines'
 'Kiwifruit' 'Pummelo' 'Satsuma' 'Rutabagas' 'Greens' 'Pears' 'Parsnips'
 'Onions, Processed' 'Lettuce, Bibb' 'Watermelons, Seeded' 'Mangoes'
 'Olives' 'Temples' 'Misc Asian Vegetables' 'Cantaloupe'
 'Tejocote (mexican Hawthorn)' 'Cranberries' 'Rhubarb' 'Beet Tops'
 'Fiddle Head Ferns' 'Peaches' 'Cherries' 'Apricots' 'Nectarines' 'Plums'
 'Prunes' 'Pomegranates' 'Persimmons' 'Passion Fruit' 'Dandelion Greens'
 'Black Currants' 'Misc Citrus' 'Lee Citrus' 'Homelyfruit'
 'Broccoli Rabe (rappini)' 'Apple Pears' 'Lettuce, Boston, Red'
 'Lettuce, Oak Leaf, Green' 'Fruits Other' 'Cherimoya'
 'Jerusalem Artichokes' 'Pepino' 'Red Currants' 'Radish Sprouts'
 'Loganberries' 'Kumquats']

In [9]:
#Save the filtered data into the staging folder for visualization
refrig_truck_vol_5_years.to_csv("staging/refrigerated_truck_volume.csv", index=False)