## Staging grain transporation costs from USDA data for trucks

In [1]:
import requests
import pandas as pd
from pprint import pprint
#from config import api_key

In [5]:
#Create the URL and params
url="https://agtransport.usda.gov/resource/8uye-ieij.json?"
sample_years=["2018", "2019","2020","2021","2022"]
param1="$query=select%20year,month,avg(truck)%20where%20year="
param2="%20group%20by%20year,month%20order%20by%20year,month"

In [21]:
#Get the payload
years=[]
months=[]
priceidx=[]
for year in sample_years:
        params=param1+year+param2
        response = requests.get(url,params=params).json()
        for trucking_year in response:
                
                years.append(trucking_year['year'])
                months.append(trucking_year['month'])
                priceidx.append(float(trucking_year['avg_truck']))

grain_trucking_cost_df=pd.DataFrame(zip(years,months,priceidx))
grain_trucking_cost_df.columns=["Year","Month","Trucking Cost Index"]
#grain_trucking_volume_df.set_index('Year')
grain_trucking_cost_df

    Year Month  Trucking Cost Index
0   2018     1               202.00
1   2018     2               204.50
2   2018     3               200.50
3   2018     4               207.60
4   2018     5               217.75
5   2018     6               218.25
6   2018     7               217.00
7   2018     8               216.00
8   2018     9               219.60
9   2018    10               226.75
10  2018    11               221.50
11  2018    12               209.60
12  2019     1               200.00
13  2019     2               201.25
14  2019     3               206.60
15  2019     4               210.25
16  2019     5               212.00
17  2019     6               206.40
18  2019     7               204.50
19  2019     8               201.50
20  2019     9               202.40
21  2019    10               205.00
22  2019    11               206.00
23  2019    12               205.00
24  2020     1               204.75
25  2020     2               195.00
26  2020     3               183.00
27  2020     4               167.25
28  2020     5               160.40
29  2020     6               162.00
30  2020     7               163.50
31  2020     8               163.20
32  2020     9               162.00
33  2020    10               160.25
34  2020    11               163.20
35  2020    12               173.75
36  2021     1               180.60
37  2021     2               196.75
38  2021     3               212.75
39  2021     4               210.25
40  2021     5               215.80
41  2021     6               220.75
42  2021     7               224.00
43  2021     8               224.80
44  2021     9               227.00
45  2021    10               243.80
46  2021    11               250.25
47  2021    12               244.50
48  2022     1               249.80
49  2022     2               270.50
50  2022     3               342.50
51  2022     4               343.25
52  2022     5               374.00
53  2022     6               386.25
54  2022     7               363.80
55  2022     8               334.25
56  2022     9               335.00
57  2022    10               349.80
58  2022    11               352.75
59  2022    12               316.00

In [22]:
#Save the dataframe to a csv in the staging folder
grain_trucking_cost_df.to_csv("staging/grain_trucking_cost.csv",index=False)

In [23]:
grain_trucking_volume_df = pd.read_csv("staging/grain_trucking_cost.csv")
grain_trucking_volume_df

    Year  Month  Trucking Cost Index
0   2018      1               202.00
1   2018      2               204.50
2   2018      3               200.50
3   2018      4               207.60
4   2018      5               217.75
5   2018      6               218.25
6   2018      7               217.00
7   2018      8               216.00
8   2018      9               219.60
9   2018     10               226.75
10  2018     11               221.50
11  2018     12               209.60
12  2019      1               200.00
13  2019      2               201.25
14  2019      3               206.60
15  2019      4               210.25
16  2019      5               212.00
17  2019      6               206.40
18  2019      7               204.50
19  2019      8               201.50
20  2019      9               202.40
21  2019     10               205.00
22  2019     11               206.00
23  2019     12               205.00
24  2020      1               204.75
25  2020      2               195.00
26  2020      3               183.00
27  2020      4               167.25
28  2020      5               160.40
29  2020      6               162.00
30  2020      7               163.50
31  2020      8               163.20
32  2020      9               162.00
33  2020     10               160.25
34  2020     11               163.20
35  2020     12               173.75
36  2021      1               180.60
37  2021      2               196.75
38  2021      3               212.75
39  2021      4               210.25
40  2021      5               215.80
41  2021      6               220.75
42  2021      7               224.00
43  2021      8               224.80
44  2021      9               227.00
45  2021     10               243.80
46  2021     11               250.25
47  2021     12               244.50
48  2022      1               249.80
49  2022      2               270.50
50  2022      3               342.50
51  2022      4               343.25
52  2022      5               374.00
53  2022      6               386.25
54  2022      7               363.80
55  2022      8               334.25
56  2022      9               335.00
57  2022     10               349.80
58  2022     11               352.75
59  2022     12               316.00

In [ ]:
filepath="Resources/Refrigerated_Truck_Volumes.csv"
refrigerated_truck_volume = pd.read_csv("Resources/Refrigerated_Truck_Volumes.csv")
refrigerated_truck_volume.tail(20)

In [ ]:
refrig_truck_vol_5_years = refrigerated_truck_volume.loc[(refrigerated_truck_volume['Year']>2017) & (refrigerated_truck_volume['Year'] <2023),:]
refrig_truck_vol_5_years

In [ ]:
print(f"Number of commodities trucked: {refrig_truck_vol_5_years['Commodity'].nunique()}")

In [ ]:
refrig_truck_vol_5_years.to_csv("staging/refrigerated_truck_volume.csv", index=False)